# Generated by Django 3.0.7 on 2020-06-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thumb',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.TextField(),
        ),
    ]
