# Generated by Django 3.0.7 on 2020-06-30 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0009_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_researcher_app.Restaurant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_researcher_app.User'),
        ),
    ]
