# Generated by Django 3.0.7 on 2020-07-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0011_auto_20200703_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurants',
            field=models.ManyToManyField(to='restaurant_researcher_app.Restaurant'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_researcher_app.Restaurant'),
        ),
    ]
