# Generated by Django 3.0.7 on 2020-07-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0012_auto_20200703_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurants',
        ),
    ]
