# Generated by Django 3.0.7 on 2020-07-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0015_auto_20200703_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant_name',
            field=models.TextField(null=True),
        ),
    ]
