# Generated by Django 3.0.7 on 2020-07-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0018_starrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='starrating',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restaurant_researcher_app.Restaurant'),
        ),
    ]
