# Generated by Django 3.0.7 on 2020-07-06 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0019_starrating_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='starrating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='restaurant_researcher_app.StarRating'),
        ),
    ]
