# Generated by Django 3.0.7 on 2020-07-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0020_auto_20200706_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='starrating',
        ),
        migrations.AddField(
            model_name='starrating',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='restaurant_researcher_app.Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
