# Generated by Django 3.0.7 on 2020-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_researcher_app', '0022_remove_starrating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
